[build]
  publish = "public"
  command = "./netlify-build.sh"

[build.environment]
  HUGO_VERSION = "0.118.2"
  HUGO_ENV = "production"

[context.production]
  command = "./netlify-build.sh"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.118.2"

[context.branch-deploy]
  command = "hugo --buildDrafts --buildFuture --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.118.2"